#!/bin/bash

# Arguments
ARG1="${HOME}/dotlrt/inputs/WRF_Output/wrfout_d02_2019-05-26_12_00_00"
ARG2="${HOME}/dotlrt/output/wrf_output"

# Palallel
# mpirun -np 1 ./dot ${ARG1} ${ARG2}

# Sequential
./dot ${ARG1} ${ARG2}

