SHELL=/bin/sh
# 
# List of Source objects for each main calling sequence 
# (main first, subroutines second)

mods = DOTLRT_variables.o profiles.o DOTLRT_output.o scan_mod.o scan_control.o scan_routines.o scan_var_assign.o scan_var_control.o  scan_read_input.o absh2o.o absn2.o calc_fbw_temp_weight_scat.o calc_mon_temp_weight_scat.o calc_passband_freq.o calcprofile.o calc_tot_ext.o configure.o construct_surf.o core95.o d3lec.o do_tb_gvh94.o Dtb94.o fresnel_refl.o gaussj.o gaussq.o GeoJacobian.o get_instr_spec.o GetProfile.o Hg_phmat.o hydro_master_derivatives.o InterpSR.o Jacobian.o jacobi.o kirchoff_ocean_refl.o mrt.o o2abs.o rd.o rf.o RT_Jacobian.o Tb94.o handle_err.o read_WRF_netcdf.o get_data.o read_namel.o write_output.o

test = $(mods) scan.o 

ncwrite   = simple_write.o
ncread    = $(mods) simple_read.o netcdf_utilities_mod.o
ncwriteme = write_netcdf_file.o
ncutils   = netcdf_utilities_mod.o
dotvar    = DOTLRT_variables.o
# Tunable parameters
#
# FC		Name of the fortran compiling system to use
# FFLAGS	Flags to the compiler
#               -O optimize
#               -o output specified
#               -g use debugger
# LDFLAGS	Flags to the loader
# LIBS		List of libraries
# CMD		Name of the executable
#
# SGI unique

NCDIR = $(HOME)/local

FC = gfortran
FFLAGS = -g -Wall -Wextra -I$(NCDIR)/include -fbounds-check -Wuninitialized -Wunused -ffree-line-length-none -fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow 	
LIBS = -L$(NCDIR)/lib -lnetcdf -lnetcdff
LDFLAGS =       	

## Linux unique
#NETCDFINC = /lib64/gfortran/modules
#NETCDFLIB = /usr/lib64/
#PGPLOTLIB = /usr/lib64/
#PGPLOTINC = /usr/lib64/
#
##
## Suggested debugging flags:
##  -g                  add debugging information to executable
##  -Wuninitialized     catch uninitialized variables
##  -Wunused            issue warning for unused variables - keeps code clean
##  -fbacktrace         runtime errors try to print out a stack backtrace
##  -fbounds-check      add runtime-checking for out-of-range array indices
##  -ffpe-trap=invalid,zero,overflow
##                      stop on floating point errors
#
#FC =		gfortran
#FFLAGS =	-Wall -Wextra -I$(NETCDFINC) -Wno-compare-reals -Wno-do-subscript -fbounds-check -fbacktrace -g
#LIBS =		-L$(NETCDFLIB) -lnetcdf -lnetcdff
#
# end machine uniquescan_var_assign.o
CMD =		a.out
.f:
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $<

# scan files
#scan_plot.o: scan_plot.f90
#	$(FC) $(FFLAGS) -c scan_plot.f90
scan.o: scan.f90
	$(FC) $(FFLAGS) -c scan.f90
scan_routines.o: scan_routines.f90
	$(FC) $(FFLAGS) -c scan_routines.f90
scan_mod.o: scan_mod.f90
	$(FC) $(FFLAGS) -c scan_mod.f90
scan_read_input.o: scan_read_input.f90
	$(FC) $(FFLAGS) -c scan_read_input.f90
scan_control.o: scan_control.f90
	$(FC) $(FFLAGS) -c scan_control.f90
scan_var_control.o: scan_var_control.f90
	$(FC) $(FFLAGS) -c scan_var_control.f90
scan_var_assign.o: scan_var_assign.f90
	$(FC) $(FFLAGS) -c scan_var_assign.f90


# DOTLRT Files
DOTLRT_variables.o: DOTLRT_variables.f90
	$(FC) $(FFLAGS) -c DOTLRT_variables.f90
profiles.o: profiles.f90
	$(FC) $(FFLAGS) -c profiles.f90
DOTLRT_output.o: DOTLRT_output.f90
	$(FC) $(FFLAGS) -c DOTLRT_output.f90
DOTLRT_main.o: DOTLRT_main.f90
	$(FC) $(FFLAGS) -c DOTLRT_main.f90
absh2o.o: absh2o.f90
	$(FC) $(FFLAGS) -c absh2o.f90
absn2.o: absn2.f90
	$(FC) $(FFLAGS) -c absn2.f90
calc_fbw_temp_weight_scat.o: calc_fbw_temp_weight_scat.f90
	$(FC) $(FFLAGS) -c calc_fbw_temp_weight_scat.f90
calc_mon_temp_weight_scat.o: calc_mon_temp_weight_scat.f90
	$(FC) $(FFLAGS) -c calc_mon_temp_weight_scat.f90
calc_passband_freq.o: calc_passband_freq.f90
	$(FC) $(FFLAGS) -c calc_passband_freq.f90
calcprofile.o: calcprofile.f90
	$(FC) $(FFLAGS) -c calcprofile.f90
calc_tot_ext.o: calc_tot_ext.f90
	$(FC) $(FFLAGS) -c calc_tot_ext.f90
configure.o: configure.f90
	$(FC) $(FFLAGS) -c configure.f90
construct_surf.o: construct_surf.f90
	$(FC) $(FFLAGS) -c -ffree-line-length-none construct_surf.f90
core95.o: core95.f90
	$(FC) $(FFLAGS) -c core95.f90
d3lec.o: d3lec.f90
	$(FC) $(FFLAGS) -c d3lec.f90
do_tb_gvh94.o: do_tb_gvh94.f90
	$(FC) $(FFLAGS) -c do_tb_gvh94.f90
Dtb94.o: Dtb94.f90
	$(FC) $(FFLAGS) -c Dtb94.f90
fresnel_refl.o: fresnel_refl.f90
	$(FC) $(FFLAGS) -c fresnel_refl.f90
gaussj.o: gaussj.f90
	$(FC) $(FFLAGS) -c gaussj.f90
gaussq.o: gaussq.f90
	$(FC) $(FFLAGS) -c gaussq.f90
GeoJacobian.o: GeoJacobian.f90
	$(FC) $(FFLAGS) -c GeoJacobian.f90
get_instr_spec.o: get_instr_spec.f90
	$(FC) $(FFLAGS) -c get_instr_spec.f90
GetProfile.o: GetProfile.f90
	$(FC) $(FFLAGS) -c GetProfile.f90
Hg_phmat.o: Hg_phmat.f90
	$(FC) $(FFLAGS) -c Hg_phmat.f90
hydro_master_derivatives.o: hydro_master_derivatives.f90
	$(FC) $(FFLAGS) -c hydro_master_derivatives.f90
InterpSR.o: InterpSR.f90
	$(FC) $(FFLAGS) -c InterpSR.f90
Jacobian.o: Jacobian.f90
	$(FC) $(FFLAGS) -c Jacobian.f90
jacobi.o: jacobi.f90
	$(FC) $(FFLAGS) -c jacobi.f90
kirchoff_ocean_refl.o: kirchoff_ocean_refl.f90
	$(FC) $(FFLAGS) -c kirchoff_ocean_refl.f90
mrt.o: mrt.f90
	$(FC) $(FFLAGS) -c mrt.f90
o2abs.o: o2abs.f90
	$(FC) $(FFLAGS) -c o2abs.f90
read_namel.o: read_namel.f90
	$(FC) $(FFLAGS) -c read_namel.f90
rd.o: rd.f90
	$(FC) $(FFLAGS) -c rd.f90
rf.o: rf.f90
	$(FC) $(FFLAGS) -c rf.f90
RT_Jacobian.o: RT_Jacobian.f90
	$(FC) $(FFLAGS) -c RT_Jacobian.f90
Tb94.o: Tb94.f90
	$(FC) $(FFLAGS) -c Tb94.f90
handle_err.o: handle_err.f90
	$(FC) $(FFLAGS) -c handle_err.f90
read_WRF_netcdf.o: read_WRF_netcdf.f90
	$(FC) $(FFLAGS) -c read_WRF_netcdf.f90
get_data.o: get_data.f90
	$(FC) $(FFLAGS) -c get_data.f90
write_output.o: write_output.f90
	$(FC) $(FFLAGS) -c write_output.f90
simple_write.o: simple_write.f90
	$(FC) $(FFLAGS) -c simple_write.f90
simple_read.o: simple_read.f90
	$(FC) $(FFLAGS) -c simple_read.f90
write_netcdf_file.o: write_netcdf_file.f90
	$(FC) $(FFLAGS) -c write_netcdf_file.f90
netcdf_utilities_mod.o: netcdf_utilities_mod.f90
	$(FC) $(FFLAGS) -c netcdf_utilities_mod.f90

# make command list

test: $(test) 
	$(FC) $(FFLAGS) $(test) $(LIBS) -o test.out

ncwrite: $(ncwrite)
	$(FC) $(FFLAGS) $(ncwrite) $(LIBS) -o nc_write.out

#ncread: ncutils dotvar dotout scanmod prof $(ncread) $(mods)
#	$(FC) $(FFLAGS) $(ncread) $(mods) $(LIBS) -o ncread

ncread: $(ncread) $(mods)
	$(FC) $(FFLAGS) $(ncutils) $(ncread) $(mods) $(LIBS) -o ncread

dotvar: $(dotvar)
	$(FC) $(FFLAGS) $(dotvar) $(LIBS) -c DOTLRT_variables.f90

ncutils: $(ncutils)
	$(FC) $(FFLAGS) $(ncutils) $(LIBS) -c netcdf_utilities_mod.f90

prof: profiles.o
	$(FC) $(FFLAGS) profiles.o $(LIBS) -c profiles.f90

scanmod: scan_mod.o
	$(FC) $(FFLAGS) scan_mod.o $(LIBS) -c scan_mod.f90

dotout: DOTLRT_output.o
	$(FC) $(FFLAGS) DOTLRT_output.o $(LIBS) -c DOTLRT_output.f90

clean:
	-rm -f *.o *.out *.mod *.stb core


